#! /usr/bin/env python
""" Calculates Beam Block from json_file and tif_file. """

from __future__ import print_function

import argparse
# import pyart

from beam_block.core import beam_block_json

def main():
    """ Reads all prior functions and produces pbb, cbb and flags.
    The data is then put into dictionaries and added to a radar object,
    which then the radar object is written to netCDF. """
    # Creating func and argument parser for terminal use of this file.
    parser = argparse.ArgumentParser(
        description='Create a radar object with beam block fields.')
    parser.add_argument(
        'json_file', type=str, help='JSON file to use for calculations.')
    parser.add_argument(
        'tif_file', type=str, help='Tif file to use as terrain data.')
    parser.add_argument(
        'out_file', type=str, help='Out file path and name to use.')
    args = parser.parse_args()

    print('')
    print('## Creating a radar object with beam block fields')
    print('')

    # radar = pyart.io.read(args.radar_file)

    pbb_all, cbb_all = beam_block_json.beam_block_json(
        args.json, args.tif_file, 1.0)

    pbb_flags, cbb_flags = beam_block_json._beam_block_flag(
        pbb_all, cbb_all, 0.0, 0.0)

if __name__ == '__main__':
    main()
